### ISSUE TITLE
Template et première brique

### ISSUE THREAD

**Issue by couleurmate** [couleurmate/cycloperativa#1]
Donc, t'auras le temps de faire les prémisses du website. N'hésite pas à me dire si je dois m'en occuper seul. Pas de soucis !

**Comment by leeuwerck** [comment]
c'est toujours au programme, et je te tiens au courant si ça change. :)
est-ce que tu peux m'envoyer la liste dont tu avais pris note dans ton
carnet ?

2015-09-02 12:34 GMT+02:00 couleurmate notifications@github.com:

**Comment by couleurmate** [comment]
J'ai tout tapé dans le wiki ;)
